### ISSUE TITLE
Not an issue: Add your extension to official list ;-)

### ISSUE THREAD

**Issue by joundso** [edvinsyk/quarto-landscape#1]
Hi @edvinsyk 
thanks for the great extension!
Maybe it would be useful for others, to find your extension in the [official list of quarto extensions](https://quarto.org/docs/extensions/). There is a way mentioned at the top about how to get your extension published.
Would like to see it there one day. =)

Update: Saw, that the same proposal was already given [here](https://github.com/quarto-dev/quarto-cli/discussions/6104#discussioncomment-10408122). Feel free to just close this "issue".

Best regards!

**Comment by edvinsyk** [comment]
Hey @joundso, it has actually already been added into quarto, so it should be possible to use now/soon with the dev version, see here: https://github.com/quarto-dev/quarto-cli/pull/10581

Thanks for letting me know anyway :), glad you like the extension
